CC = g++
CFLAGS = -Wall -Werror -Wshadow -pedantic -std=gnu++11
INCLUDE_FLAGS = -I/usr/include/SDL2/
LIBRARY_FLAGS = -lSDL2

graphics:
	$(CC) main.cpp -o grun $(CFLAGS) $(INCLUDE_FLAGS) $(LIBRARY_FLAGS)
